{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
    harness.io/managed: "true"
  name: {{ include "httpbin.fullname" . }}
spec:
  host: {{ include "httpbin.fullname" . }}-svc-primary
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
{{- end }}
