apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: {{ include "httpbin.fullname" . }}
 annotations:
  kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
     paths:
      - backend:
          serviceName: {{ include "httpbin.fullname" . }}
          servicePort: 80
