apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "httpbin.fullname" . }}-svc-primary
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
     paths:
      - backend:
          serviceName: {{ include "httpbin.fullname" . }}-svc-primary
          servicePort: 80
