{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "httpbin.fullname" . }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "httpbin.fullname" . }}
  annotations:
    harness.io/managed: "true"
spec:
  gateways:
    - {{ include "httpbin.fullname" . }}
  hosts:
    {{- toYaml .Values.istio.hosts | nindent 4}}
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: {{ include "httpbin.fullname" . }}-svc-primary
      weight: 100
    - destination:
        host: {{ include "httpbin.fullname" . }}-svc-stage
      weight: 0

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
    harness.io/managed: "true"
  name: {{ include "httpbin.fullname" . }}
spec:
  host: {{ include "httpbin.fullname" . }}-svc-primary
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
{{- end }}
