apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpbin.fullname" . }}-svc-primary
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
  annotations:
    harness.io/primary-service: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "httpbin.selectorLabels" . | nindent 4 }}
