{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    harness.io/managed: "true"
  name: {{ include "httpbin.fullname" . }}
spec:
  gateways:
    - {{ include "httpbin.fullname" . }}
  hosts:
    {{- toYaml .Values.istio.hosts | nindent 4}}
  http:
  - route:
    - destination:
        host: {{ include "httpbin.fullname" . }}-svc-primary
{{- end }}
