# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ include "job.fullname" . }}
#   labels:
#     {{- include "job.labels" . | nindent 4 }}
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       {{- include "job.selectorLabels" . | nindent 6 }}
#   template:
#     metadata:
#       labels:
#         {{- include "job.selectorLabels" . | nindent 8 }}
#     spec:
#     {{- with .Values.imagePullSecrets }}
#       imagePullSecrets:
#         {{- toYaml . | nindent 8 }}
#     {{- end }}
#       serviceAccountName: {{ include "job.serviceAccountName" . }}
#       securityContext:
#         {{- toYaml .Values.podSecurityContext | nindent 8 }}
#       containers:
#         - name: {{ .Chart.Name }}
#           securityContext:
#             {{- toYaml .Values.securityContext | nindent 12 }}
#           image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - name: http
#               containerPort: 80
#               protocol: TCP
#           livenessProbe:
#             httpGet:
#               path: /
#               port: http
#           readinessProbe:
#             httpGet:
#               path: /
#               port: http
#           resources:
#             {{- toYaml .Values.resources | nindent 12 }}
#       {{- with .Values.nodeSelector }}
#       nodeSelector:
#         {{- toYaml . | nindent 8 }}
#       {{- end }}
#     {{- with .Values.affinity }}
#       affinity:
#         {{- toYaml . | nindent 8 }}
#     {{- end }}
#     {{- with .Values.tolerations }}
#       tolerations:
#         {{- toYaml . | nindent 8 }}
#     {{- end }}

{{ range .Values.jobParams }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "job.fullname" . }}-{{.Values.jobId }}
  labels:
    {{- include "job.labels" . | nindent 4 }}
  annotation:
    jobId: {{ .Values.jobId }}
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "{{ .Values.jobParameters }}"]
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
