harnessApiVersion: '1.0'
type: APPLICATION_MANIFEST
gitFileConfig:
  branch: master
  connectorName: harnessu_admin_workloads
  useBranch: true
  useInlineServiceDefinition: false
kustomizeConfig:
  kustomizeDirPath: wordpress
storeType: KustomizeSourceRepo
